### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by benazir0** [onnela-lab/beiwe-ios#1]
I'm using MacOS High Sierra, version 10.13.5 and Xcode version: 9.4 (9F1027a).
I have lots of build errors. Here are the things I did:

- Deleted pod folder and podfile.lock file
- Updated cocoapods, ran pod install. It couldn't download the swift 4 branches mentioned on the podfile as they do not exist.
- Then I went to the repositories and added the latest version on the podfile. It downloaded and installed the pod files after that. But still I get 165 compilation error on Hakuba. There are also other errors. Please see the screenshot.

![screen shot 2018-06-04 at 4 03 57 pm](https://user-images.githubusercontent.com/39503792/40900874-062638c4-6811-11e8-99ef-c2768dfc8020.png)

-

**Comment by ZexingGao** [comment]
same here!

**Comment by ZexingGao** [comment]
Hi Benazir0, do you know how to fix this Hakuba error? I have same issue with you!

**Comment by benazir0** [comment]
Hi @ZexingGao, I think Hakuba works only with old version of swift and Xcode. The Hakuba repo hasn't been updated for a long time. Unfortunately, I'm busy with other projects, therefore, I don't have time right now to fix the issues. Let me know how you go.

**Comment by ZexingGao** [comment]
Hi @benazir0, I fixed this error. You are right about Hakuba. You need to change pod file from "pod 'Hakuba', :git => 'https://github.com/eskizyen/Hakuba.git', :branch => 'Swift3'" to "pod 'Hakuba'". It maybe failed again, but if you try several times pod install and update, with different branches, then it would work! But there are still bugs after this error. I remember you need to delete "!" and "?" somewhere (Xcode would tell you). Also there is a function called "isPassword", you need to  change it to "self.isPassword". After all those changes you will be good. I have the running app on my laptop now. Feel free to ask further questions.

**Comment by biblicabeebli** [comment]
This is an old swift compatibility issue, it is no longer the case.
