### ISSUE TITLE
Beiwe ios app does not log patient after registration 

### ISSUE THREAD

**Issue by arisfil79** [onnela-lab/beiwe-ios#10]
Hi, i created my own backend, i Registwred a patient with a twmporary code however when I ise the Beiwe2 app I can’t pass through the registration screen.

At the backend side I see my patient (ios) and there is an orange unregister button.

Also it seems that the server does not get any data in the s3 bucket apart from the creation ones

I have a mac os mojave and used the proposed aws setup 

Thanks

**Comment by biblicabeebli** [comment]
This was resolved quite a while ago, numerous other at-registration-time bugs have also been resolvedd.
