### ISSUE TITLE
PermissionScope Error - App terminates

### ISSUE THREAD

**Issue by hectorhm98** [onnela-lab/beiwe-ios#11]
I upgrade the iOS version and Swift version to make it work in new Xcode, but at the moment of guarantee the notifications and location permissions after register the app terminates showing this msg: 

> 2019-12-17 12:33:16.646735+0100 UShineDbg[22383:666693] -[PermissionScope.PermissionScope requestNotifications]: unrecognized selector sent to instance 0x7f89d580c600
2019-12-17 12:33:16.653524+0100 UShineDbg[22383:666693] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[PermissionScope.PermissionScope requestNotifications]: unrecognized selector sent to instance 0x7f89d580c600'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c4f02e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50b97b20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23c6ff94 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   UIKitCore                           0x00007fff4787df39 -[UIResponder doesNotRecognizeSelector:] + 302
	4   CoreFoundation                      0x00007fff23c53dac ___forwarding___ + 1436
	5   CoreFoundation                      0x00007fff23c55f38 _CF_forwarding_prep_0 + 120
	6   UIKitCore                           0x00007fff47850dfa -[UIApplication sendAction:to:from:forEvent:] + 83
	7   UIKitCore                           0x00007fff4722ac22 -[UIControl sendAction:to:forEvent:] + 223
	8   UIKitCore                           0x00007fff4722af6c -[UIControl _sendActionsForEvents:withEvent:] + 398
	9   UIKitCore                           0x00007fff47229ecb -[UIControl touchesEnded:withEvent:] + 481
	10  UIKitCore                           0x00007fff4788bc1d -[UIWindow _sendTouchesForEvent:] + 2604
	11  UIKitCore                           0x00007fff4788d524 -[UIWindow sendEvent:] + 4596
	12  UIKitCore                           0x00007fff47868427 -[UIApplication sendEvent:] + 356
	13  UIKitCore                           0x00007fff478e987e __dispatchPreprocessedEventFromEventQueue + 6847
	14  UIKitCore                           0x00007fff478ec344 __handleEventQueueInternal + 5980
	15  CoreFoundation                      0x00007fff23bb2221 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	16  CoreFoundation                      0x00007fff23bb214c __CFRunLoopDoSource0 + 76
	17  CoreFoundation                      0x00007fff23bb1924 __CFRunLoopDoSources0 + 180
	18  CoreFoundation                      0x00007fff23bac62f __CFRunLoopRun + 1263
	19  CoreFoundation                      0x00007fff23babe16 CFRunLoopRunSpecific + 438
	20  GraphicsServices                    0x00007fff38438bb0 GSEventRunModal + 65
	21  UIKitCore                           0x00007fff4784fb48 UIApplicationMain + 1621
	22  UShineDbg                           0x0000000106d95acb main + 75
	23  libdyld.dylib                       0x00007fff51a1dc25 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

The problem is that somehow the app sends an abort signal due to an uncaught exception.

**Comment by rawalvarun** [comment]
@hectorhm98 @biblicabeebli 
We are facing the exact same issue due to which the app crashes.
Has any fix for this been figured out yet ?

**Comment by rawalvarun** [comment]
I just checked the updated repo code 
In the following commit, it seems that permissionScope pod and use has been removed :
https://github.com/onnela-lab/beiwe-ios/commit/6a99e1736eb69e4b11cb3a4904fd1829ee17a55e

**Comment by hectorhm98** [comment]
Yes, it was due to permissionScope, we remove it and change how we ask permissions , but as you say it was removed also in the newest commit.
