### ISSUE TITLE
Facing SegFault 11 while building in Xcode 12 - Swift 4 

### ISSUE THREAD

**Issue by rawalvarun** [onnela-lab/beiwe-ios#16]
Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)

2.	While evaluating request TypeCheckSourceFileRequest(source_file "beiwe/Extensions/EurekaSwiftValidatorComponents.swift")

3.	While type-checking '_SVTextRow' (at beiwe/Extensions/EurekaSwiftValidatorComponents.swift:166:6)

4.	While type-checking protocol conformance to 'SVRow' beiwe/Extensions/EurekaSwiftValidatorComponents.swift:166:6 - line:207:1] RangeText="class _SVTextRow<Cell: _SVFieldCell<String>>: FieldRow<Cell>, SVRow where Cell: BaseCell, Cell: CellType, Cell: TextFieldCell, Cell.Value == String {
    public required init(tag: String?) {
        super.init(tag: tag)
    }

    open var errorColor: UIColor {
        get {
            return self.cell.errorColor
        }
        set {
            self.cell.errorColor = newValue
        }
    }

    open var rules: [Rule]? {
        get {
            return self.cell.rules
        }
        set {
            self.cell.setRules(newValue)
        }
    }

    open var autoValidation: Bool {
        get {
            return self.cell.autoValidation
        }
        set {
            self.cell.autoValidation = newValue
        }
    }

    open var valid: Bool {
        get {
            return self.cell.valid
        }
    }

    open func validate() {
        self.cell.validate()
    }
")

error: Segmentation fault: 11

**Comment by rawalvarun** [comment]
beiwe/Extensions/EurekaSwiftValidatorComponents.swift:166:29: note: superclass constraint 'Cell' : '_SVFieldCell<String>' written here
open class _SVTextRow<Cell: _SVFieldCell<String>>: FieldRow<Cell>, SVRow where Cell: BaseCell, Cell: CellType, Cell: TextFieldCell, Cell.Value == String {
                            ^
                                                                                                                   ^
beiwe/Extensions/EurekaSwiftValidatorComponents.swift:166:29: note: conformance constraint 'Cell': 'TextFieldCell' implied here
open class _SVTextRow<Cell: _SVFieldCell<String>>: FieldRow<Cell>, SVRow where Cell: BaseCell, Cell: CellType, Cell: TextFieldCell, Cell.Value == String {
                            ^
beiwe/Extensions/EurekaSwiftValidatorComponents.swift:180:14: error: overriding non-open property outside of its defining module
    open var rules: [Rule]? {
             ^
beiwe/Extensions/EurekaSwiftValidatorComponents.swift:180:14: error: property 'rules' with type '[Rule]?' cannot override a property with type '[ValidationRuleHelper<Cell.Value>]'
    open var rules: [Rule]? {
             ^
beiwe-os/Pods/Eureka/Source/Core/Row.swift:85:30: note: attempt to override property here
    public internal(set) var rules: [ValidationRuleHelper<T>] = []

**Comment by biblicabeebli** [comment]
Hi, thanks for posting this.
Can you tell me what branch/commit you are on when you see this?  I don't believe we are hitting this issue.

**Comment by rawalvarun** [comment]
The branch is master

I was trying to fix the following issue  : https://github.com/xmartlabs/Eureka/issues/2057
by trying to bump then Eureka version from 4.1.1 to 5.3.2

This was leading to these errors

**Comment by rawalvarun** [comment]
But now even after reverting back to 4.1.1, we're facing this same error 

Segmentation Fault : "While type-checking protocol conformance to 'SVRow'..."

**Comment by rawalvarun** [comment]
These lines are problematic to be specific : 

https://github.com/onnela-lab/beiwe-ios/blob/master/Beiwe/Extensions/EurekaSwiftValidatorComponents.swift#L166-L207

Eureka 4.1.1
Xcode 12.0
Swift 4.0
Mac OS 10.15.7

**Comment by rawalvarun** [comment]
also facing the following issue : 

https://forums.swift.org/t/swift-5-compiler-crashes-on-when-attmepting-to-build-specific-file/22702/2

**Comment by biblicabeebli** [comment]
This is very old and not a known occurrence, if this is still relevant somewhere please post a new issue referencing this one.
