### ISSUE TITLE
New update of app not working on appstore

### ISSUE THREAD

**Issue by mikej561** [onnela-lab/beiwe-ios#17]
Hello,

after update of the app it no longer works. Everytime when I try to register a new patient the app crashes and sends just the identifier back to the server. Android app works fine and deployment should be OK too. Could you test it guys? Thank you very much @biblicabeebli

**Comment by biblicabeebli** [comment]
Hi, yeah we have a bug in the ios app, we are working on the fix.  our bad.
Also tracking this issue over on the backend repo: https://github.com/onnela-lab/beiwe-backend/issues/187

**Comment by mikej561** [comment]
Awesome! Thank you. Do you think when there could be new version out? @biblicabeebli  Thanks, Michal and the ctu team

**Comment by biblicabeebli** [comment]
Hi Michal, just quoting Josh from the other thread:
we're working on a fix, but the Beiwe2 iOS app is stuck in a loop of appeals with the App Store Review Board.

My own commentary:
They've... randomly forgotten that they already reviewed and okayed the Beiwe app as an acceptable data collection platform.  They did this when we sent in the bug fix.  It is stupid.

**Comment by biblicabeebli** [comment]
This was fixed late last week.
