### ISSUE TITLE
Sometimes the app loads a black screen when launched

### ISSUE THREAD

**Issue by biblicabeebli** [onnela-lab/beiwe-ios#20]
(Creating this issue to track it, don't have any information at time of posting.)

**Comment by biblicabeebli** [comment]
oops, there is already discussion on this on https://github.com/onnela-lab/beiwe-ios/issues/13

Leaving this issue open as it is  specific and 13 is discussing several items, and I believe those are resolved to some extent.

**Comment by nponarul** [comment]
@biblicabeebli Do you happen to know what the status on this is? I am happy to help test anything on this - we had a collaborator asking about it so I just wanted to check in.

**Comment by biblicabeebli** [comment]
No update on the issue.  My time is currently spent on end of year deadlines, mostly with the backend codebase.

**Comment by clementzach** [comment]
I've done some testing, and I'm able to replicate this bug by:
1. Switching from the app to the Home Screen
2. Waiting 10 minutes
3. Reopening the app

I have not seen this bug on shorter app durations.

**Comment by clementzach** [comment]
Another update:
Setting the "Duration before auto-logout" to 10 seconds made the black screen occur very quickly. I believe this issue is caused by the app crashing during auto-logout.

**Comment by biblicabeebli** [comment]
> Another update:
> 
> Setting the "Duration before auto-logout" to 10 seconds made the black screen occur very quickly. I believe this issue is caused by the app crashing during auto-logout. 

!!!!!!!!!!!!!

Not sure if I have the voodoo skills yet to debug, but thanks, this is helpful.

**Comment by kwcarlso** [comment]
@clementzach thanks for looking into this, very helpful.

**Comment by biblicabeebli** [comment]
I "accidentally" fixed this in either 2.1.3 or 2.2.0.
This bug turned out to be a combination of asynchronous runtime bugs plus the poor use of promisekit throughout the app.  In cleaning up the at-launch behavior several problems were resolved.

At this time I no longer can replicate this issue so I am marking it as closed.
