### ISSUE TITLE
Trying to get Beiwe up and running

### ISSUE THREAD

**Issue by mehalley** [onnela-lab/beiwe-ios#21]
I'm trying to get the Beiwe iOS front-end up and running for a project I am working on. I keep running into the problem that "no such module 'Hakuba'" I uninstalled and reinstalled the cocoapods but it keeps coming up. All my research on the error says it has something to do with using an Xcode project instead of an Xcode workspace, can anybody help me with this issue?

**Comment by biblicabeebli** [comment]
Sorry, not sure why that is happening for you.  We may need to update libraries etc., please let us know if you are able to determine the root of the problem.
