### ISSUE TITLE
SurveyCell.swift

### ISSUE THREAD

**Issue by mehalley** [onnela-lab/beiwe-ios#23]
I've been having issues with the SurveyCell.swift file. I'm getting a "type is ambiguous for type lookup in this context" and all the research I've done says that in order to get rid of this error I need to be more specific. I'm not sure how to be more specific since I'm not super familiar with the code, would anyone be able to help with this?

<img width="843" alt="Screen Shot 2022-01-20 at 1 30 53 PM" src="https://user-images.githubusercontent.com/62576991/150400705-358166df-f963-4c31-ad02-4bdcb2a080a8.png">
<img width="838" alt="Screen Shot 2022-01-20 at 1 31 02 PM" src="https://user-images.githubusercontent.com/62576991/150400709-5283d42d-9ade-4c2d-ab32-84f026a27f79.png">
<img width="248" alt="Screen Shot 2022-01-20 at 1 31 29 PM" src="https://user-images.githubusercontent.com/62576991/150400718-f117db3a-03fb-48f3-b6b5-4c49957f9b53.png">

**Comment by biblicabeebli** [comment]
(Thanks for posting)
I think this is a missing type specification, the error statement is the compiler saying it just needs more info to give you better help.  I'm out of practice on the Swift details but I finally have a mac and will be getting into the swift code hopefully as soon as next week.

is this your new code, or existing code?

**Comment by mehalley** [comment]
This is the existing code

**Comment by biblicabeebli** [comment]
well, crap...

**Comment by biblicabeebli** [comment]
This was resolved a while ago, at this point I have 100% forgotten how.
