### ISSUE TITLE
Compiling issue with the ResearchKit Pod on macs with M-Series ARM cpus

### ISSUE THREAD

**Issue by biblicabeebli** [onnela-lab/beiwe-ios#27]
I'm not asking for anyone's help with this, but I'm writing it up in case someone else encounters it, especially @biblicabeebli @zagorsky .

I'm trying to compile the beiwe-ios app, and two things are going wrong with the ResearchKit pod and preventing me from building to the simulator:
1. After I run `pod install`, in Podfile.lock, ResearchKit's checksum hash changed from `b948fcbadd4454d6b835d2b64471980a467a96a7` to `454bd5d013f5d6817b1c893ebe471a082061ceee`
2. When I click Run in XCode and try to build the app to the simulator, I get several errors saying "Umbrella for module ResearchKit already covers this directory", and lots of warnings saying "Umbrella header for module ResearchKit does not include header [header-name]"

I suspect that the wrong version of ResearchKit is being installed, and that's what's causing the "umbrella" errors.  But I don't know how to install the right version of ResearchKit.

XCode version 13.4.1, Mac OS Monterey 12.4, M2 processor.

**Comment by biblicabeebli** [comment]
issue iss now visible at https://github.com/onnela-lab/beiwe-ios/issues/27

**Comment by zagorsky** [comment]
@biblicabeebli are you also encountering this issue?  Or are you only reposting the issue I encountered?

**Comment by biblicabeebli** [comment]
I was just reposting, couldn't transfer the issue from the other repo.

**Comment by biblicabeebli** [comment]
I moved to an m2 mac a month ago, I never had this issue.  It was probably a missing brew dependency.

**Comment by reyvababtista** [comment]
I am encountering this issue too. How did you fix this? @biblicabeebli 

XCode 15.2, MacOS Sonoma 14.3.1, M3 Max

**Comment by biblicabeebli** [comment]
Do the clean build folder, quit xcode, pod install, open xcode and build - dance.

Whenever I do anything with pod installs in xcode I invariably have to do that, I just never encountered the variation that involves researchkit.

And you want the 2.5 branch.

**Comment by reyvababtista** [comment]
> Do the clean build folder, quit xcode, pod install, open xcode and build - dance.
> 
> Whenever I do anything with pod installs in xcode I invariably have to do that, I just never encountered the variation that involves researchkit.
> 
> And you want the 2.5 branch.

I found another error after doing that. This one's from `GoogleDataTransport - GDTCORClock: "A function declaration without a prototype is deprecated in all versions of C"`. Any insights? @biblicabeebli

**Comment by biblicabeebli** [comment]
No clue. You can make an issue, but whatever is going on is specific to your local configuration.

**Comment by reyvababtista** [comment]
Okay. I tried to redo all the steps, I found . This was done on M3 Max, Sonoma 14.3.1, Xcode 15.2, Swift 5.9.2.

1. Clone project, switch to branch 2.5.
2. `pod install`
3. Open Xcode, copy GoogleService-Info.plist file.
4. Build.
5. Error: `Could not build Objective-C module 'ResearchKit'. Umbrella for module 'ResearchKit' already covers this directory`
6. Clean build folder.
7. Close Xcode.
8. `pod install`
9. Open Xcode
10. Build.
11. Error: `Could not build Objective-C module 'ResearchKit'. Umbrella for module 'ResearchKit' already covers this directory`

The `GoogleDataTransport ` did not seem to happen again. Anyway, I am stuck on trying to build this. I have attached the full build log into this message. Any advice? @biblicabeebli 

[Build Beiwe2_2024-03-01T08-47-18.txt](https://github.com/onnela-lab/beiwe-ios/files/14462502/Build.Beiwe2_2024-03-01T08-47-18.txt)

**Comment by biblicabeebli** [comment]
Please make a new issue, this is not a reasonable location to track this.
