### ISSUE TITLE
Failed to install pods

### ISSUE THREAD

**Issue by surender-boston** [onnela-lab/beiwe-ios#3]
pod install is failed and throwing the error.
[!] Error installing PermissionScope
[!] Failed to download 'PermissionScope'.

On the GitHub page of 'PermissionScope' library, it says
"PermissionScope is no longer supported. Please use an alternative if you need updates for newer iOS 10 and 11 APIs!"

**Comment by biblicabeebli** [comment]
This is very old and no longer an issue.
