### ISSUE TITLE
iOS Image and Video Capture

### ISSUE THREAD

**Issue by hydawo** [onnela-lab/beiwe-ios#32]
Develop the ability to capture image and/or video through prompted survey. 

- This should be a **new survey type** (not a survey question type within existing survey function)
- We also want to be able to **toggle upload of a previous image** stored in camera's photo library (on a per survey basis)
- Current **scheduling infrastructure should not need modifications**
- Make **2 separate survey types** - 1 for image surveys and 1 for video surveys (this prevents users from uploading the wrong media type; i.e. user uploads video when prompted for image)
- **Image resolution constraint**? → new iPhone 14 Pro Max has 48Mp camera (vs 12Mp for most other iPhones)
- **Video duration capture limit**
- **Audio settings for video?**
- Ensure that study settings .JSON does not include image capture lines as this has produced issues with Sycamore code in the past

**Comment by biblicabeebli** [comment]
I've started reviewing all the ios ui code, survey code, etc.  Nowhere yet, but its started.

**Comment by hydawo** [comment]
@hydawo needs to look into which study is funding this and have we agreed to build it

**Comment by hydawo** [comment]
Noting a very rough estimate of 1 month development time.
