### ISSUE TITLE
ios does not update surveys other than the exact survey in a notification when it receives a notification

### ISSUE THREAD

**Issue by biblicabeebli** [onnela-lab/beiwe-ios#36]
This causes at least always available surveys that have no schedules to never update.

**Comment by biblicabeebli** [comment]
I have a fix for this (needed it to be able to Do Development)

The app sorts surveys on the main screen by time of notification receipt, and _possibly_ internal timer information too. I am attempting to preserve the current behavior, but internal timers for surveys are confirmed broken in a way that presents inconsistently/unpredictably.

**Comment by biblicabeebli** [comment]
this is long finished.

**Comment by biblicabeebli** [comment]
I think I encountered a different way in which surveys were not appropriately deleted/updated/remove/re-added on ios. Annoyingly I only have a recollection of this and no details in my brain. phooey.

**Comment by biblicabeebli** [comment]
Yeah the code that removes surveys from "activeSurveys" uses the local database as the source of truth, but I don't think we actually delete surveys that are missing when we grab the json blob for new surveys.

**Comment by biblicabeebli** [comment]
I'm pretty sure this is fixed

**Comment by hydawo** [comment]
While I haven't tested this specifically, when testing checkbox logic feature I was making changes to surveys and forcing a push notification out (usually not for the survey I was updating) and all surveys seemed to update.

I'd like to have our new RA's test this (soon), but need to complete a few other items first. Let's keep the issue open and I'm moving it to my sprint.

I don't believe you need to do anything else here @biblicabeebli...for now.
